import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import FooterSection from "@/components/footer-one";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="manrope-main bg-background">
        <Navbar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
